Pollidut/ViewModels/ComplainViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pollidut.ViewModels
{
    //printing notes
    public class ComplainViewModel
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string User { get; set; }
        public int Left { get; set; }
        public int Top { get; set; }
        public int Zindex { get; set; }
    }

}

Pollidut/Controllers/ComplainController.cs
using Pollidut.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Pollidut.ViewModels;

namespace Pollidut.Controllers
{
    public class ComplainController : Controller
    {
        // GET: Complain
        public ActionResult Index()
        {
            return View();
        }
        //Ticket Creation By Client
        public ActionResult CreateTicket()
        {
            int empId = Convert.ToInt32(Session["EmployeeId"].ToString());
            using (DataAccess.PollidutEntities db = new PollidutEntities())
            {
                var Category = (from b in db.TICKET_CATEGORY select b).ToList();
                ViewBag.Category = Category;
            }
            return View("CreateTicket");
        }
        [HttpPost]
        public JsonResult CreateNewComplain(ComplainTicket ticket)
        {
            using(PollidutEntities db=new PollidutEntities())
            {
                int empId = Convert.ToInt32(Session["EmployeeId"].ToString());
                DateTime dt=DateTime.Now;
                var tkt=new ComplainTicket()
                {
                    StatusId=1,
                    CategoryId=ticket.CategoryId,
                    SubCategoryId=ticket.SubCategoryId,
                    Mobile=ticket.Mobile,
                    Title=ticket.Title,
                    ContentText=ticket.ContentText,
                    isNotifyByEmail=ticket.isNotifyByEmail,
                    CreatedBy=empId,
                    Active=true,
                    OpenDate=dt
                };
                db.ComplainTickets.Add(tkt);
                db.SaveChanges();
            }
            
            return Json("success");
        }
        //Search Ticket By Support Center
        public ActionResult SearchTicket()
        {
            using (DataAccess.PollidutEntities db = new PollidutEntities())
            {
                var TicketStatus = (from b in db.TICKET_STATUS select b).ToList();
                ViewBag.TicketStatus = TicketStatus;
                var Category = (from b in db.TICKET_CATEGORY select b).ToList();
                ViewBag.Category = Category;
            }
            return View("SearchTicket");
        }
        public JsonResult getTickets(int statusId=0,int CategoryId=0,int SubCategoryId=0)
        {
            int empId = Convert.ToInt32(Session["EmployeeId"].ToString());
            List<SearchedTicket> tickets = new List<SearchedTicket>();
            using (PollidutEntities db = new PollidutEntities())
            {
                var searched = (from a in db.ComplainTickets where a.CreatedBy == empId select a);
                if (statusId > 0)
                {
                    searched = (from b in searched where b.StatusId == statusId select b);
                }
                if (CategoryId > 0)
                {
                    searched = (from b in searched where b.CategoryId == CategoryId select b);
                }
                if (SubCategoryId > 0)
                {
                    searched = (from b in searched where b.SubCategoryId ==SubCategoryId select b);
                }
                var Filterddata = (from d in searched
                                   select new
                                       {
                                           d.TicketId,
                                           d.TICKET_STATUS.StatusName,
                                           d.OpenDate,
                                           d.CloseDate
                                       }).ToList();
                foreach (var eachTicket in Filterddata)
                {
                    try
                    {
                        SearchedTicket ticket = new SearchedTicket();
                        int TotalConversation = (from a in db.TICKET_REPLIED where a.TicketId == eachTicket.TicketId select a).Count();
                        DateTime dt = DateTime.Now;
                        DateTime d1 = eachTicket.OpenDate == null ? dt : (DateTime)eachTicket.OpenDate;
                        DateTime d2 = eachTicket.CloseDate == null ? dt : (DateTime)eachTicket.CloseDate;
                        TimeSpan ts = d1.Subtract(d2);
                        string Difference = ts.Days.ToString() + " D. " + ts.Hours + " H. " + ts.Minutes + " M.";
                        var lastReplied = (from a in db.TICKET_REPLIED join b in db.EMPLOYEES on a.RepliedBy equals b.EMPLOYEE_ID join c in db.PERSONS on b.PERSON_ID equals c.PERSON_ID where a.TicketId == eachTicket.TicketId orderby a.RepliedTime descending select c.PERSON_NAME ).FirstOrDefault();

                        string LastRepliedFrom = "Mr. Nazmul";
                        if (lastReplied != null)
                        {
                            LastRepliedFrom = lastReplied;
                        }
                        ticket.TicketId = eachTicket.TicketId;
                        ticket.Status = eachTicket.StatusName;
                        ticket.TotalConversation = TotalConversation;
                        ticket.Duration = Difference;
                        ticket.LastRepliedFrom = LastRepliedFrom;
                        tickets.Add(ticket);
                    }
                    catch (Exception ex)
                    {
                        return Json(new { msg="failure"});
                    }
                    
                }
            }
            return Json(tickets);
        }
        //Ticket Details Open By Support Center
        public ActionResult TicketDetails(int ticketId)
        {
            return View();
        }
        public JsonResult getSubCategory(int categoryId)
        {
            using (PollidutEntities db = new PollidutEntities())
            {
                var data = (from a in db.TICKET_SUB_CATEGORY where a.CATEGORY_ID == categoryId select new
                {
                    SUB_CATEGORY_ID=a.SUB_CATEGORY_ID,
                    SUB_CATEGORY_NAME=a.SUB_CATEGORY_NAME
                }).ToList();
                return Json(data);
            }
        }
    }
}

Pollidut/Views/Complain/CreateTicket.cshtml
<div class="row" id="search-criteria-class">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    <span>Create Complain</span>
                </h4>
                @*   <span id="pie-chart-loader" class="loader">
                    <img src="../../assets/images/loaders/circular/059.gif" width="16" height="16" alt="" /></span>*@
                <a href="#" class="minimize">Minimize</a>
            </div>
            <div class="panel-body">
                <h2 id="SuccessfulMsg" style="display:none;">Your Complain Successfully Submitted.</h2>

                <form class="form-horizontal" id="form-search-employee" action="~/Complain/CreateNewComplain">

                    <div class="form-group">
                        <label class="col-lg-2 " for="complainstatus">Status</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="complainstatus" value="Initial" readonly="readonly" />
                        </div>
                    </div>


                    @*active*@
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Catagory</label>
                        <div class="col-lg-10">
                            
                            <select class="nostyle form-control resetIt" id="categoryid" name="active" style="width: 100%;">
                                <option value="0">None</option>
                                @foreach (var x in ViewBag.Category)
                                {
                                    <option value="@x.CATEGORY_ID">@x.CATEGORY_NAME</option>
                                }
                            </select>
                        </div>
                    </div>
                    @*active*@
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Sub Category</label>
                        <div class="col-lg-10">
                            <select class="nostyle form-control resetIt" id="subcategoryId" name="active" style="width: 100%;">
                                
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Mobile No.</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="mobile" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Title</label>
                        <div class="col-lg-10">
                            <input id="txttitle" class="form-control"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Content</label>
                        <div class="col-lg-10">
                            <textarea rows="10" class="form-control limit nostyle" id="txtContent" maxlength="3000"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active"></label>
                        <div class="col-lg-10">
                            <input id="chkEmailNotify" type="checkbox" /> Get Email Notification
                        </div>
                    </div>


                    @*Buttons*@
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-9">
                            <button type="button" id="btn-submit-mainform" class="btn btn-success btn-lg">Submit</button>
                        </div>
                    </div>
                </form>


            </div>

        </div>
    </div>
</div>
<script>
    $(function () {
        $('#btn-submit-mainform').click(function (e) {
            e.preventDefault();
            var ticket = {};
            ticket.StatusId = 1;
            ticket.CategoryId = $('#categoryid').val();
            ticket.SubCategoryId = $('#subcategoryId').val();
            ticket.Mobile = $('#mobile').val();
            ticket.Title = $('#txttitle').val();
            ticket.ContentText = $('#txtContent').val();
            if ($('#chkEmailNotify').is(":checked")) {
                ticket.isNotifyByEmail = true;
            }
            else {
                ticket.isNotifyByEmail = false;
            }
            
            console.log(ticket);
            var url = '@Url.Action("CreateNewComplain", "Complain")';
            $.ajax({
                type: "POST",
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                async: true,
                data: JSON.stringify({ ticket: ticket }),
                success: function (result) {
                    $('#form-search-employee').hide();
                    $('#SuccessfulMsg').show();
                },
                error: function (request, status, error) {
                    alert("Failed to save. Error Details -  Request: " + request + ", Status: " + status + ", Error: " + error);
                }
            });


            
        });
        $('#categoryid').change(function () {
            var url = '@Url.Action("getSubCategory","Complain")';

            $.ajax({
                type: "POST",
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                async: true,
                data: JSON.stringify({ categoryId: $(this).val() }),
                success: function (result) {
                    BindCombo(result, $("#subcategoryId"));
                },
                error: function (request, status, error) {
                    alert("Failed to save. Error Details -  Request: " + request + ", Status: " + status + ", Error: " + error);
                }
            });
        });
        function BindCombo(result, combo) {
            combo.empty().append('<option selected="selected"> None</option>');
            $.each(result, function () {
                combo.append($("<option></option>").val(this['SUB_CATEGORY_ID']).html(this['SUB_CATEGORY_NAME']));
            });
        }
    });
</script>

Pollidut/Views/Complain/Index.cshtml
Here is Complain Dashboard

Pollidut/Views/Complain/SearchTicket.cshtml
<div class="row" id="SearchPanel">
    <div class="col-lg-12">
        <div class="panel panel-default" id="existing-data">
            <div class="row" id="search-criteria-class">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4>
                                <span>Search Complain</span>
                            </h4>
                            @*   <span id="pie-chart-loader" class="loader">
                        <img src="../../assets/images/loaders/circular/059.gif" width="16" height="16" alt="" /></span>*@
                            <a href="#" class="minimize">Minimize</a>
                        </div>
                        <div class="panel-body">

                            <form class="form-horizontal" id="form-search-employee" action="~/Complain/CreateNewComplain">

                                <div class="form-group">
                                    <label class="col-lg-2 " for="complainstatus">Status</label>
                                    <div class="col-lg-10">
                                        <select class="nostyle form-control resetIt" id="active" name="active" style="width: 100%;">
                                            <option value="0">All</option>
                                            @foreach (var x in ViewBag.TicketStatus)
                                            {
                                                <option value="@x.StatusId">@x.StatusName</option>
                                            }
                                        </select>
                                    </div>
                                </div>


                                @*active*@
                                <div class="form-group">
                                    <label class="col-lg-2" for="active">Catagory</label>
                                    <div class="col-lg-10">
                                        <select class="nostyle form-control resetIt" id="categoryid" name="active" style="width: 100%;">
                                            <option value="0">None</option>
                                            @foreach (var x in ViewBag.Category)
                                            {
                                                <option value="@x.CATEGORY_ID">@x.CATEGORY_NAME</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                @*active*@
                                <div class="form-group">
                                    <label class="col-lg-2" for="active">Sub Catagory</label>
                                    <div class="col-lg-10">
                                        <select class="nostyle form-control resetIt" id="subcategoryId" name="active" style="width: 100%;"></select>
                                    </div>
                                </div>



                                @*Buttons*@
                                <div class="form-group">
                                    <div class="col-lg-offset-2 col-lg-9">
                                        <button type="button" id="btn-submit-mainform" class="btn btn-success btn-lg">Search</button>
                                    </div>
                                </div>
                            </form>


                        </div>

                    </div>
                </div>
            </div>
            <div class="panel-body noPad" id="SearchResultMainDiv" style="display:none;">
                <table id="searchIndent" class="table table-hover searchIndent" style="display:table;">
                    <thead>
                        <tr>
                            <th>Ticket</th>
                            <th>Status</th>
                            <th>Duration</th>
                            <th>Total Reply</th>
                            <th>Last Reply From</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody id="searchResult">
                       
                       
                    </tbody>



                </table>

            </div>



        </div>
    </div>

</div>
<script>
    function BindCombo(result, combo) {
        combo.empty().append('<option selected="selected"> None</option>');
        $.each(result, function () {
            combo.append($("<option></option>").val(this['SUB_CATEGORY_ID']).html(this['SUB_CATEGORY_NAME']));
        });
    }
    $(function () {
        $('#categoryid').change(function () {
            var url = '@Url.Action("getSubCategory","Complain")';

            $.ajax({
                type: "POST",
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                async: true,
                data: JSON.stringify({ categoryId: $(this).val() }),
                success: function (result) {
                    BindCombo(result, $("#subcategoryId"));
                },
                error: function (request, status, error) {
                    alert("Failed to save. Error Details -  Request: " + request + ", Status: " + status + ", Error: " + error);
                }
            });
        });
    });
</script>
<script>
    $(function () {
        $('#btn-submit-mainform').click(function () {
            var url = '@Url.Action("getTickets", "Complain")';

            $.ajax({
                type: "POST",
                url: url,
                contentType: "application/json; charset=utf-8",
                dataType: 'json',
                async: true,
                data: JSON.stringify({ statusId: 0,CategoryId:0,SubCategoryId:0 }),
                success: function (result) {
                    $('#SearchResultMainDiv').show();
                    $('#searchResult').empty();
                    $.each(result, function () {
                        $('#searchResult').append('<tr><td>' + this.TicketId + '</td><td>' + this.Status + '</td><td>' + this.Duration + '</td><td>' + this.TotalConversation + '</td><td>' + this.LastRepliedFrom + '</td><td><input type="button" class="btn btn-primary btnTicketDetail" value="Open Ticket" /></td></tr>')
                    });
                },
                error: function (request, status, error) {
                    alert("Failed to save. Error Details -  Request: " + request + ", Status: " + status + ", Error: " + error);
                }
            });
            $('#SearchResultMainDiv').show();
        });
        $('#SearchResultMainDiv').on('click', '.btnTicketDetail', function () {
            var currentLink = '/Complain/TicketDetails?ticketId=12';
            $.ajax({
                url: currentLink,
                async: true,
                beforeSend: function () {
                    $('div.sidenav').block({ message: '<img src="../../Assets/images/loaders/circular/001.gif" />' });
                    $('.panel-body div').removeClass('scroll');
                    $("#PartialContent").fadeOut("slow").empty();

                },
                success: function (data) {
                    $('#PartialContent').hide().html(data).fadeIn("slow");
                },
                error: function (request, status, error) {
                    alert("Error-  Request: " + request + ", Status: " + status + ", Error: " + error);
                },
                complete: function () {
                    $('div.sidenav').unblock();
                }
            });
        });
    });
</script>

Pollidut/Views/Complain/TicketDetails.cshtml
<div class="row" id="search-criteria-class">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>
                    <span>Ticket Details</span>
                </h4>
                @*   <span id="pie-chart-loader" class="loader">
                    <img src="../../assets/images/loaders/circular/059.gif" width="16" height="16" alt="" /></span>*@
                <a href="#" class="minimize">Minimize</a>
            </div>
            <div class="panel-body">

                <form class="form-horizontal" id="form-search-employee" action="~/Complain/CreateNewComplain">

                    <div class="form-group">
                        <label class="col-lg-2 " for="complainstatus">Ticket ID</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="complainstatus" value="12325" readonly="readonly" />
                        </div>
                    </div>


                    @*active*@
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Category</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="complainstatus" value="Travelling" readonly="readonly" />
                        </div>
                    </div>
                    @*active*@
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Sub Category</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="complainstatus" value="Sub Category" readonly="readonly" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Status</label>
                        <div class="col-lg-10">
                            <input class="form-control" id="complainstatus" value="Reply From Support" readonly="readonly" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Title</label>
                        <div class="col-lg-10">
                            <input class="form-control" value="Problem Defination"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Content</label>
                        <div class="col-lg-10">
                            <textarea rows="5" class="form-control limit nostyle" maxlength="100">Some Problem Defination.Details of the Problem</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Reply From Support</label>
                        <div class="col-lg-10">
                            <textarea rows="5" class="form-control limit nostyle" maxlength="100">Given Solution For the Problem Statement.</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Feedback</label>
                        <div class="col-lg-10">
                            <textarea rows="5" class="form-control limit nostyle" maxlength="100">Given Feedback.Some other Problem</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Reply From Support</label>
                        <div class="col-lg-10">
                            <textarea rows="5" class="form-control limit nostyle" maxlength="100">Given Solution For the Problem Statement</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2" for="active">Feedback</label>
                        <div class="col-lg-10">
                            <textarea rows="5" class="form-control limit nostyle" maxlength="100"></textarea>
                        </div>
                    </div>


                    @*Buttons*@
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-9">
                            <button type="button" id="btn-submit-mainform" class="btn btn-success btn-lg">Send</button>
                            <button type="button" id="btn-submit-mainform" class="btn btn-warning btn-lg">Close This Ticket</button>
                        </div>
                    </div>
                </form>


            </div>

        </div>
    </div>
</div>